### ISSUE TITLE
Fetch and Display HK-ADC data in ProtoCUBES monitor

### ISSUE THREAD

**Issue by sonals301** [tstana/CitirocUI#6]
Display latest values fetched from CUBES HK-ADC - Battery Voltage(V), Battery Current(A) and Citiroc temperature(deg C) once Req_HK button is tapped, along with other values.

Create separate group box for this at the bottom

**Comment by tstana** [comment]
Branch `HK_ADC_Data` opened for this issue has been merged to `master`. Closing issue.
